language: c
compiler:
    - gcc
dist: focal
cache: ccache

git:
  depth: 10
  quiet: false

if: tag IS blank

branches:
  only:
    - /^master$/

install:
    - sudo apt-add-repository 'deb http://archive.ubuntu.com/ubuntu focal main'
    - sudo apt-get update -qq
    - sudo apt-get install -qq ccache make gcc
script:
    - export PATH=/usr/lib/ccache:$PATH
    - make BPI-R64_defconfig
    - make -s
    - mv images/rootfs.cpio.gz rootfs_bpi-r64.cpio.gz
    - make clean
    - echo -e "BR2_arm=y\nBR2_cortex_a7=y" >> .config
    - make -s
    - mv images/rootfs.cpio.gz rootfs_bpi-r2.cpio.gz
before_deploy:
    # Set up git user name and tag this commit
    - git config --local user.name "Frank Wunderlich"
    - git config --local user.email "frank-w@public-files.de"
    - export TRAVIS_TAG=${TRAVIS_TAG:-"CI-BUILD-$(date +'%Y%m%d_%H%M%S')-$(git log --format=%h -1)"}
    - git tag $TRAVIS_TAG
deploy:
    provider: releases
    token: $GITHUB_TOKEN
    file_glob: true
    file:
    - "*.cpio.gz"
    name: $TRAVIS_BRANCH-$(date +'%Y%m%d%H%M%S')
    skip_cleanup: true
    cleanup: false
    on:
        all_branches: true
